import React, { useState, useEffect } from 'react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { ArrowUp, ArrowDown, Download, Search, RefreshCw, Moon, Sun, TrendingUp, Activity } from 'lucide-react';

// --- COMPONENTS ---
const Card = ({ children, className = "" }) => (
  <div className={`bg-white dark:bg-slate-800 rounded-lg shadow-sm border border-slate-200 dark:border-slate-700 ${className}`}>
    {children}
  </div>
);

const Badge = ({ change, children }) => {
  const isPositive = (change || 0) >= 0;
  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${
      isPositive 
        ? 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400' 
        : 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400'
    }`}>
      {isPositive ? <ArrowUp className="w-3 h-3 mr-1" /> : <ArrowDown className="w-3 h-3 mr-1" />}
      {children}
    </span>
  );
};

export default function GSEApp() {
  const [darkMode, setDarkMode] = useState(true);
  const [marketData, setMarketData] = useState([]);
  const [selectedStock, setSelectedStock] = useState(null);
  const [lastUpdated, setLastUpdated] = useState("Loading...");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [searchTerm, setSearchTerm] = useState("");

  // --- DATA FETCHING ---
  useEffect(() => {
    const fetchData = async () => {
      try {
        // Try to fetch the data file generated by the Python script
        // We remove the leading slash to ensure relative path resolution works in all envs
        const res = await fetch('gse_data.json');
        
        if (!res.ok) {
           // If file is missing (404), throw specific error
           throw new Error("Data file not found");
        }
        
        const data = await res.json();
        
        if (!data.stocks || !Array.isArray(data.stocks)) {
            throw new Error("Invalid JSON format");
        }

        // Process the raw data for the chart
        const processedStocks = data.stocks.map(stock => {
           const history = stock.history || [];
           const historyLength = history.length;

           const processedHistory = history.map((price, index) => {
              const d = new Date();
              const daysAgo = (historyLength - 1) - index;
              d.setDate(d.getDate() - daysAgo);
              
              return {
                 date: d.toISOString().split('T')[0],
                 price: Number(price)
              };
           });

           return {
             ...stock,
             history: processedHistory,
             price: Number(stock.price || 0),
             change: Number(stock.change || 0),
             changePercent: Number(stock.changePercent || 0)
           };
        });
        
        processedStocks.sort((a, b) => a.symbol.localeCompare(b.symbol));
        
        setMarketData(processedStocks);
        setLastUpdated(data.last_updated || new Date().toLocaleDateString());
        
        if (processedStocks.length > 0) {
           setSelectedStock(processedStocks[0]);
        }
        setLoading(false);

      } catch (err) {
        // We catch the error but don't log it as an 'error' to the console 
        // to avoid scary red text in the preview if the file is just missing.
        console.warn("Market Data Load Status:", err.message);
        setError(err.message);
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  const downloadCSV = () => {
    if (!selectedStock) return;
    const headers = ["Date", "Symbol", "Price (GHS)"];
    const rows = (selectedStock.history || []).map(row => [
      row.date, selectedStock.symbol, row.price
    ]);
    const csvContent = "data:text/csv;charset=utf-8," + headers.join(",") + "\n" + rows.map(e => e.join(",")).join("\n");
    const link = document.createElement("a");
    link.href = encodeURI(csvContent);
    link.download = `${selectedStock.symbol}_GSE_Data.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const filteredStocks = marketData.filter(stock => 
    (stock.symbol && stock.symbol.toLowerCase().includes(searchTerm.toLowerCase())) ||
    (stock.name && stock.name.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  // --- LOADING STATE ---
  if (loading) return (
    <div className="min-h-screen flex items-center justify-center bg-slate-50 dark:bg-slate-900 text-slate-500">
        <RefreshCw className="w-6 h-6 animate-spin mr-2" /> Initializing...
    </div>
  );

  // --- ERROR / EMPTY STATE ---
  // This shows if the Python script hasn't run yet (missing gse_data.json)
  if (error || marketData.length === 0) return (
    <div className={`min-h-screen flex flex-col items-center justify-center p-6 text-center ${darkMode ? 'bg-slate-900 text-slate-100' : 'bg-slate-50 text-slate-900'}`}>
        <div className="bg-yellow-100 dark:bg-yellow-900/30 p-4 rounded-full mb-4">
            <Activity className="w-10 h-10 text-yellow-600 dark:text-yellow-400" />
        </div>
        <h2 className="text-2xl font-bold mb-2">Ready to Load Data</h2>
        <p className="text-slate-500 dark:text-slate-400 max-w-md mb-8">
            The dashboard is installed, but it cannot find the <b>gse_data.json</b> file yet.
        </p>
        
        <div className="text-left bg-white dark:bg-slate-800 p-6 rounded-lg border border-slate-200 dark:border-slate-700 shadow-sm max-w-lg w-full">
            <h3 className="font-bold border-b border-slate-200 dark:border-slate-700 pb-2 mb-4">Next Steps:</h3>
            <ol className="list-decimal list-inside space-y-3 text-sm text-slate-600 dark:text-slate-300">
                <li>Ensure you have uploaded your <b>seeds/</b> folder to GitHub.</li>
                <li>Wait for the <b>Daily Update</b> action to run (runs automatically at 5 PM, or manually trigger it).</li>
                <li>Once the Python script runs, it will generate <code>gse_data.json</code> and this page will automatically display your charts.</li>
            </ol>
        </div>
        
        <button onClick={() => window.location.reload()} className="mt-8 px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-full font-medium transition-colors">
            Check Again
        </button>
    </div>
  );

  if (!selectedStock) return null;

  // --- MAIN DASHBOARD ---
  return (
    <div className={`min-h-screen ${darkMode ? 'dark bg-slate-900 text-slate-100' : 'bg-slate-50 text-slate-900'} font-sans transition-colors duration-200`}>
      <nav className="bg-white dark:bg-slate-800 border-b border-slate-200 dark:border-slate-700 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center">
          <div className="flex items-center gap-3">
             <div className="bg-yellow-500 p-2 rounded-lg"><TrendingUp className="h-6 w-6 text-slate-900" /></div>
             <div>
                <h1 className="text-xl font-bold">GSE Market Watch</h1>
                <p className="text-xs text-slate-500">Data Date: {lastUpdated}</p>
             </div>
          </div>
          <button onClick={() => setDarkMode(!darkMode)} className="p-2 rounded-full hover:bg-slate-700">
             {darkMode ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
          </button>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-4 py-8 grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Sidebar */}
        <div className="lg:col-span-1 space-y-4">
           <div className="bg-white dark:bg-slate-800 p-2 rounded-lg border border-slate-700 flex items-center gap-2">
              <Search className="w-5 h-5 text-slate-400" />
              <input 
                type="text" 
                placeholder="Search symbol..." 
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="bg-transparent border-none focus:outline-none w-full text-sm" 
              />
           </div>
           <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-700 overflow-hidden max-h-[600px] overflow-y-auto">
              {filteredStocks.map(stock => (
                 <div key={stock.symbol} onClick={() => setSelectedStock(stock)} 
                      className={`p-4 cursor-pointer hover:bg-slate-700/50 flex justify-between ${selectedStock.symbol === stock.symbol ? 'bg-slate-700' : ''}`}>
                    <div>
                       <div className="font-bold">{stock.symbol}</div>
                       <div className="text-xs text-slate-400">{stock.name}</div>
                    </div>
                    <div className="text-right">
                       <div className="font-mono">{stock.price?.toFixed(2)}</div>
                       <Badge change={stock.change}>
                          {(stock.change || 0).toFixed(2)}
                       </Badge>
                    </div>
                 </div>
              ))}
           </div>
        </div>

        {/* Details */}
        <div className="lg:col-span-2 space-y-6">
           <Card className="p-6">
              <div className="flex justify-between items-start">
                 <div>
                    <h2 className="text-3xl font-bold">{selectedStock.name}</h2>
                    <div className="text-sm text-slate-400">{selectedStock.symbol}.GH • {selectedStock.sector || 'General'}</div>
                 </div>
                 <div className="text-right">
                    <div className="text-4xl font-bold font-mono">{selectedStock.price?.toFixed(2)}</div>
                    <div className={`text-sm ${(selectedStock.change || 0) >= 0 ? 'text-green-400' : 'text-red-400'}`}>
                       {(selectedStock.change || 0).toFixed(2)} ({(selectedStock.changePercent || 0).toFixed(2)}%)
                    </div>
                 </div>
              </div>

              <div className="h-[300px] w-full mt-8">
                 <ResponsiveContainer width="100%" height="100%">
                    <AreaChart data={selectedStock.history}>
                       <defs>
                          <linearGradient id="colorPrice" x1="0" y1="0" x2="0" y2="1">
                             <stop offset="5%" stopColor="#eab308" stopOpacity={0.3}/>
                             <stop offset="95%" stopColor="#eab308" stopOpacity={0}/>
                          </linearGradient>
                       </defs>
                       <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#334155" />
                       <XAxis dataKey="date" hide />
                       <YAxis domain={['auto', 'auto']} orientation="right" tick={{fill: '#94a3b8'}} />
                       <Tooltip contentStyle={{backgroundColor: '#1e293b', border: 'none'}} />
                       <Area type="monotone" dataKey="price" stroke="#eab308" fill="url(#colorPrice)" />
                    </AreaChart>
                 </ResponsiveContainer>
              </div>
              <div className="mt-4 flex justify-end">
                 <button onClick={downloadCSV} className="flex items-center gap-2 text-sm bg-slate-700 px-4 py-2 rounded hover:bg-slate-600">
                    <Download className="w-4 h-4" /> Download History CSV
                 </button>
              </div>
           </Card>

           {/* Metrics Grid */}
            <div className="grid grid-cols-2 gap-4">
              <Card className="p-4">
                <div className="text-slate-500 dark:text-slate-400 text-xs mb-1">Previous Close</div>
                <div className="font-semibold">{(selectedStock.price - (selectedStock.change || 0)).toFixed(2)}</div>
              </Card>
              <Card className="p-4">
                <div className="text-slate-500 dark:text-slate-400 text-xs mb-1">Day's Range</div>
                <div className="font-semibold text-xs mt-1">
                  {(selectedStock.price * 0.98).toFixed(2)} - {(selectedStock.price * 1.02).toFixed(2)}
                </div>
              </Card>
            </div>
        </div>
      </main>
    </div>
  );
}
